"""initial schema

Revision ID: 4a9d77a6cc23
Revises: 
Create Date: 2026-08-28 00:27:45.989385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a9d77a6cc23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='assignmentstatus').create(op.get_bind())
    sa.Enum('ARTICLE', 'QUESTIONNAIRE', name='assignmenttype').create(op.get_bind())
    sa.Enum('GENERAL', 'PATIENT_REGISTERED', 'ARTICLE_ASSIGNED', 'QUESTIONNAIRE_ASSIGNED', 'QUESTIONNAIRE_COMPLETED', 'CONTACT_REQUESTED', 'PROGRAM_PURCHASE_REQUESTED', 'PROGRAM_ACCESS_GRANTED', name='notificationtype').create(op.get_bind())
    sa.Enum('PERSONAL_DATA_PROCESSING', 'MEDICAL_DATA_PROCESSING', 'ASSISTANT_CONTACT', 'ANALYTICS_PROCESSING', name='consenttype').create(op.get_bind())
    sa.Enum('REFERRAL_CREATED', 'LINK_SENT', 'LINK_OPENED', 'REGISTRATION_COMPLETED', 'CONSENT_GIVEN', 'QUESTIONNAIRE_STARTED', 'QUESTIONNAIRE_COMPLETED', 'ARTICLE_READ', 'CONTACT_REQUESTED', 'ASSISTANT_CALL_ATTEMPTED', 'ASSISTANT_CONTACTED', 'APPOINTMENT_BOOKED', 'APPOINTMENT_ATTENDED', 'PACKAGE_OFFERED', 'PAYMENT_LINK_SENT', 'PACKAGE_PURCHASED', 'REFUND_CREATED', 'PROGRAM_STARTED', 'PROGRAM_COMPLETED', 'PROGRAM_IN_PROGRESS', name='eventtype').create(op.get_bind())
    sa.Enum('KVB_DOCTOR', 'PSYCHIATRY_EXISTING', 'CHECKUP', 'OTHER', name='referralsource').create(op.get_bind())
    sa.Enum('CREATED', 'LINK_SENT', 'OPENED', 'REGISTERED', 'CANCELLED', name='referralstatus').create(op.get_bind())
    sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='programenrollmentstatus').create(op.get_bind())
    sa.Enum('ARTICLE', 'QUESTIONNAIRE', 'CONSULTATION', name='programitemtype').create(op.get_bind())
    sa.Enum('RUB', 'UNIT', name='programcurrency').create(op.get_bind())
    sa.Enum('IN_PROGRESS', 'COMPLETED', name='questionnairesubmissionstatus').create(op.get_bind())
    sa.Enum('TEXT', 'NUMBER', 'BOOLEAN', 'SCALE', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', name='questiontype').create(op.get_bind())
    sa.Enum('ADD', 'REMOVE', name='doctortagoverrideaction').create(op.get_bind())
    sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitationstatus').create(op.get_bind())
    sa.Enum('DOCTOR', 'PATIENT', 'RELATIVE', name='invitationtype').create(op.get_bind())
    sa.Enum('REGISTRATION', 'AUTHENTICATION', name='webauthnchallengetype').create(op.get_bind())
    sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='actiontokentype').create(op.get_bind())
    sa.Enum('ACTIVE', 'DETACHED', name='relativepatientstatus').create(op.get_bind())
    sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'DETACHED', name='doctorpatientstatus').create(op.get_bind())
    sa.Enum('MALE', 'FEMALE', 'OTHER', 'NOT_SPECIFIED', name='gender').create(op.get_bind())
    sa.Enum('SUPERUSER', 'PATIENT', 'DOCTOR', 'RELATIVE', 'MED_ASSISTANT', name='userrole').create(op.get_bind())
    op.create_table('specialities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consultation_name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('consultation_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialities_name'), 'specialities', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_is_system'), 'tags', ['is_system'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'NOT_SPECIFIED', name='gender', create_type=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_blocked'), 'users', ['is_blocked'], unique=False)
    op.create_table('action_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('token_type', postgresql.ENUM('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='actiontokentype', create_type=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_tokens_expires_at'), 'action_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_action_tokens_token_hash'), 'action_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_action_tokens_token_type'), 'action_tokens', ['token_type'], unique=False)
    op.create_index(op.f('ix_action_tokens_user_id'), 'action_tokens', ['user_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pro_content', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_created_by_user_id'), 'articles', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_articles_is_hidden'), 'articles', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_articles_pro_content'), 'articles', ['pro_content'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('speciality_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_profiles_speciality_id'), 'doctor_profiles', ['speciality_id'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    op.create_table('med_assistant_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_med_assistant_profiles_user_id'), 'med_assistant_profiles', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', postgresql.ENUM('GENERAL', 'PATIENT_REGISTERED', 'ARTICLE_ASSIGNED', 'QUESTIONNAIRE_ASSIGNED', 'QUESTIONNAIRE_COMPLETED', 'CONTACT_REQUESTED', 'PROGRAM_PURCHASE_REQUESTED', 'PROGRAM_ACCESS_GRANTED', name='notificationtype', create_type=False), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('channels_json', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('passkey_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('transports_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passkey_credentials_credential_id'), 'passkey_credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_passkey_credentials_user_id'), 'passkey_credentials', ['user_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('pro_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profiles_record_id'), 'patient_profiles', ['record_id'], unique=True)
    op.create_index(op.f('ix_patient_profiles_user_id'), 'patient_profiles', ['user_id'], unique=True)
    op.create_table('programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pro_content', sa.Boolean(), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', postgresql.ENUM('RUB', 'UNIT', name='programcurrency', create_type=False), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_created_by_user_id'), 'programs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_programs_is_hidden'), 'programs', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_programs_is_popular'), 'programs', ['is_popular'], unique=False)
    op.create_index(op.f('ix_programs_pro_content'), 'programs', ['pro_content'], unique=False)
    op.create_index(op.f('ix_programs_title'), 'programs', ['title'], unique=False)
    op.create_table('questionnaires',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pro_content', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('copied_from_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['copied_from_id'], ['questionnaires.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaires_copied_from_id'), 'questionnaires', ['copied_from_id'], unique=False)
    op.create_index(op.f('ix_questionnaires_created_by_user_id'), 'questionnaires', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_questionnaires_is_hidden'), 'questionnaires', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_questionnaires_pro_content'), 'questionnaires', ['pro_content'], unique=False)
    op.create_index(op.f('ix_questionnaires_title'), 'questionnaires', ['title'], unique=False)
    op.create_table('relative_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relative_profiles_user_id'), 'relative_profiles', ['user_id'], unique=True)
    op.create_table('speciality_tag_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('speciality_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('speciality_id', 'tag_id', name='uq_speciality_tag')
    )
    op.create_index(op.f('ix_speciality_tag_links_speciality_id'), 'speciality_tag_links', ['speciality_id'], unique=False)
    op.create_index(op.f('ix_speciality_tag_links_tag_id'), 'speciality_tag_links', ['tag_id'], unique=False)
    op.create_table('user_role_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', postgresql.ENUM('SUPERUSER', 'PATIENT', 'DOCTOR', 'RELATIVE', 'MED_ASSISTANT', name='userrole', create_type=False), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_role_links_role'), 'user_role_links', ['role'], unique=False)
    op.create_index(op.f('ix_user_role_links_user_id'), 'user_role_links', ['user_id'], unique=False)
    op.create_table('webauthn_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenge_type', postgresql.ENUM('REGISTRATION', 'AUTHENTICATION', name='webauthnchallengetype', create_type=False), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_challenges_challenge'), 'webauthn_challenges', ['challenge'], unique=True)
    op.create_index(op.f('ix_webauthn_challenges_challenge_type'), 'webauthn_challenges', ['challenge_type'], unique=False)
    op.create_index(op.f('ix_webauthn_challenges_expires_at'), 'webauthn_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_webauthn_challenges_user_id'), 'webauthn_challenges', ['user_id'], unique=False)
    op.create_table('article_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('max_progress_percent', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'patient_id', name='uq_article_patient_progress')
    )
    op.create_index(op.f('ix_article_progress_article_id'), 'article_progress', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_progress_patient_id'), 'article_progress', ['patient_id'], unique=False)
    op.create_table('article_tag_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'tag_id', name='uq_article_tag')
    )
    op.create_index(op.f('ix_article_tag_links_article_id'), 'article_tag_links', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_tag_links_tag_id'), 'article_tag_links', ['tag_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', postgresql.ENUM('PERSONAL_DATA_PROCESSING', 'MEDICAL_DATA_PROCESSING', 'ASSISTANT_CONTACT', 'ANALYTICS_PROCESSING', name='consenttype', create_type=False), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('document_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_accepted'), 'consent_records', ['accepted'], unique=False)
    op.create_index(op.f('ix_consent_records_consent_type'), 'consent_records', ['consent_type'], unique=False)
    op.create_index(op.f('ix_consent_records_created_at'), 'consent_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_consent_records_patient_id'), 'consent_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consent_records_recorded_by_user_id'), 'consent_records', ['recorded_by_user_id'], unique=False)
    op.create_table('contact_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('allow_assistant_contact', sa.Boolean(), nullable=False),
    sa.Column('do_not_call', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_preferences_do_not_call'), 'contact_preferences', ['do_not_call'], unique=False)
    op.create_index(op.f('ix_contact_preferences_patient_id'), 'contact_preferences', ['patient_id'], unique=True)
    op.create_index(op.f('ix_contact_preferences_updated_by_user_id'), 'contact_preferences', ['updated_by_user_id'], unique=False)
    op.create_table('content_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_type', postgresql.ENUM('ARTICLE', 'QUESTIONNAIRE', name='assignmenttype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='assignmentstatus', create_type=False), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=True),
    sa.Column('questionnaire_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assignments_article_id'), 'content_assignments', ['article_id'], unique=False)
    op.create_index(op.f('ix_content_assignments_assigned_by_user_id'), 'content_assignments', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_content_assignments_assignment_type'), 'content_assignments', ['assignment_type'], unique=False)
    op.create_index(op.f('ix_content_assignments_patient_id'), 'content_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_content_assignments_questionnaire_id'), 'content_assignments', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_content_assignments_status'), 'content_assignments', ['status'], unique=False)
    op.create_table('doctor_patient_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'REJECTED', 'DETACHED', name='doctorpatientstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('detached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'patient_id', name='uq_doctor_patient')
    )
    op.create_index(op.f('ix_doctor_patient_links_doctor_id'), 'doctor_patient_links', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_links_patient_id'), 'doctor_patient_links', ['patient_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_links_status'), 'doctor_patient_links', ['status'], unique=False)
    op.create_table('doctor_tag_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('action', postgresql.ENUM('ADD', 'REMOVE', name='doctortagoverrideaction', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'tag_id', name='uq_doctor_tag_override')
    )
    op.create_index(op.f('ix_doctor_tag_overrides_action'), 'doctor_tag_overrides', ['action'], unique=False)
    op.create_index(op.f('ix_doctor_tag_overrides_doctor_id'), 'doctor_tag_overrides', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_tag_overrides_tag_id'), 'doctor_tag_overrides', ['tag_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invitation_type', postgresql.ENUM('DOCTOR', 'PATIENT', 'RELATIVE', name='invitationtype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitationstatus', create_type=False), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'NOT_SPECIFIED', name='gender', create_type=False), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('speciality_id', sa.Uuid(), nullable=True),
    sa.Column('doctor_profile_id', sa.Uuid(), nullable=True),
    sa.Column('patient_profile_id', sa.Uuid(), nullable=True),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('relationship_degree', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_accepted_by_user_id'), 'invitations', ['accepted_by_user_id'], unique=False)
    op.create_index(op.f('ix_invitations_created_by_user_id'), 'invitations', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_invitations_doctor_profile_id'), 'invitations', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_expires_at'), 'invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invitations_invitation_type'), 'invitations', ['invitation_type'], unique=False)
    op.create_index(op.f('ix_invitations_patient_profile_id'), 'invitations', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_invitations_record_id'), 'invitations', ['record_id'], unique=False)
    op.create_index(op.f('ix_invitations_speciality_id'), 'invitations', ['speciality_id'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_table('patient_program_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('purchase_requested', sa.Boolean(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'program_id', name='uq_patient_program_access')
    )
    op.create_index(op.f('ix_patient_program_access_is_active'), 'patient_program_access', ['is_active'], unique=False)
    op.create_index(op.f('ix_patient_program_access_patient_id'), 'patient_program_access', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_program_access_program_id'), 'patient_program_access', ['program_id'], unique=False)
    op.create_index(op.f('ix_patient_program_access_purchase_requested'), 'patient_program_access', ['purchase_requested'], unique=False)
    op.create_index(op.f('ix_patient_program_access_updated_by_user_id'), 'patient_program_access', ['updated_by_user_id'], unique=False)
    op.create_table('program_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCELLED', name='programenrollmentstatus', create_type=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('in_progress_event_at', sa.DateTime(), nullable=True),
    sa.Column('completed_event_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'program_id', name='uq_patient_program_enrollment')
    )
    op.create_index(op.f('ix_program_enrollments_patient_id'), 'program_enrollments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_program_enrollments_program_id'), 'program_enrollments', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_enrollments_status'), 'program_enrollments', ['status'], unique=False)
    op.create_table('program_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doctor_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('day_from', sa.Integer(), nullable=False),
    sa.Column('day_to', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'order_index', name='uq_program_stage_order')
    )
    op.create_index(op.f('ix_program_stages_day_from'), 'program_stages', ['day_from'], unique=False)
    op.create_index(op.f('ix_program_stages_day_to'), 'program_stages', ['day_to'], unique=False)
    op.create_index(op.f('ix_program_stages_order_index'), 'program_stages', ['order_index'], unique=False)
    op.create_index(op.f('ix_program_stages_program_id'), 'program_stages', ['program_id'], unique=False)
    op.create_table('program_tag_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'tag_id', name='uq_program_tag')
    )
    op.create_index(op.f('ix_program_tag_links_program_id'), 'program_tag_links', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_tag_links_tag_id'), 'program_tag_links', ['tag_id'], unique=False)
    op.create_table('questionnaire_tag_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_id', 'tag_id', name='uq_questionnaire_tag')
    )
    op.create_index(op.f('ix_questionnaire_tag_links_questionnaire_id'), 'questionnaire_tag_links', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_tag_links_tag_id'), 'questionnaire_tag_links', ['tag_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', postgresql.ENUM('TEXT', 'NUMBER', 'BOOLEAN', 'SCALE', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', name='questiontype', create_type=False), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('scale_min_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scale_max_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_id', 'order_index', name='uq_questionnaire_question_order')
    )
    op.create_index(op.f('ix_questions_order_index'), 'questions', ['order_index'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_questions_questionnaire_id'), 'questions', ['questionnaire_id'], unique=False)
    op.create_table('relative_patient_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('relative_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_degree', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'DETACHED', name='relativepatientstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('detached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['relative_id'], ['relative_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_id', 'patient_id', name='uq_relative_patient')
    )
    op.create_index(op.f('ix_relative_patient_links_patient_id'), 'relative_patient_links', ['patient_id'], unique=False)
    op.create_index(op.f('ix_relative_patient_links_relative_id'), 'relative_patient_links', ['relative_id'], unique=False)
    op.create_index(op.f('ix_relative_patient_links_status'), 'relative_patient_links', ['status'], unique=False)
    op.create_table('program_stage_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', postgresql.ENUM('ARTICLE', 'QUESTIONNAIRE', 'CONSULTATION', name='programitemtype', create_type=False), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=True),
    sa.Column('questionnaire_id', sa.Uuid(), nullable=True),
    sa.Column('speciality_id', sa.Uuid(), nullable=True),
    sa.Column('consultation_title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('consultation_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['program_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', 'order_index', name='uq_program_stage_item_order')
    )
    op.create_index(op.f('ix_program_stage_items_article_id'), 'program_stage_items', ['article_id'], unique=False)
    op.create_index(op.f('ix_program_stage_items_item_type'), 'program_stage_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_program_stage_items_order_index'), 'program_stage_items', ['order_index'], unique=False)
    op.create_index(op.f('ix_program_stage_items_questionnaire_id'), 'program_stage_items', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_program_stage_items_speciality_id'), 'program_stage_items', ['speciality_id'], unique=False)
    op.create_index(op.f('ix_program_stage_items_stage_id'), 'program_stage_items', ['stage_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'order_index', name='uq_question_option_order')
    )
    op.create_index(op.f('ix_question_options_order_index'), 'question_options', ['order_index'], unique=False)
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('questionnaire_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=True),
    sa.Column('program_stage_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='questionnairesubmissionstatus', create_type=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['program_stage_id'], ['program_stages.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_submissions_patient_id'), 'questionnaire_submissions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_submissions_program_id'), 'questionnaire_submissions', ['program_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_submissions_program_stage_id'), 'questionnaire_submissions', ['program_stage_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_submissions_questionnaire_id'), 'questionnaire_submissions', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_submissions_status'), 'questionnaire_submissions', ['status'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', postgresql.ENUM('CREATED', 'LINK_SENT', 'OPENED', 'REGISTERED', 'CANCELLED', name='referralstatus', create_type=False), nullable=False),
    sa.Column('source', postgresql.ENUM('KVB_DOCTOR', 'PSYCHIATRY_EXISTING', 'CHECKUP', 'OTHER', name='referralsource', create_type=False), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('invitation_id', sa.Uuid(), nullable=True),
    sa.Column('speciality_id', sa.Uuid(), nullable=False),
    sa.Column('speciality_name_snapshot', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('is_psychiatric_speciality_snapshot', sa.Boolean(), nullable=False),
    sa.Column('record_id_snapshot', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('link_sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_created_by_user_id'), 'referrals', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_doctor_id'), 'referrals', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_referrals_invitation_id'), 'referrals', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_referrals_is_psychiatric_speciality_snapshot'), 'referrals', ['is_psychiatric_speciality_snapshot'], unique=False)
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_referrals_record_id_snapshot'), 'referrals', ['record_id_snapshot'], unique=False)
    op.create_index(op.f('ix_referrals_source'), 'referrals', ['source'], unique=False)
    op.create_index(op.f('ix_referrals_speciality_id'), 'referrals', ['speciality_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_index(op.f('ix_referrals_token_hash'), 'referrals', ['token_hash'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('REFERRAL_CREATED', 'LINK_SENT', 'LINK_OPENED', 'REGISTRATION_COMPLETED', 'CONSENT_GIVEN', 'QUESTIONNAIRE_STARTED', 'QUESTIONNAIRE_COMPLETED', 'ARTICLE_READ', 'CONTACT_REQUESTED', 'ASSISTANT_CALL_ATTEMPTED', 'ASSISTANT_CONTACTED', 'APPOINTMENT_BOOKED', 'APPOINTMENT_ATTENDED', 'PACKAGE_OFFERED', 'PAYMENT_LINK_SENT', 'PACKAGE_PURCHASED', 'REFUND_CREATED', 'PROGRAM_STARTED', 'PROGRAM_COMPLETED', 'PROGRAM_IN_PROGRESS', name='eventtype', create_type=False), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('speciality_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('program_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_actor_user_id'), 'events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_events_doctor_id'), 'events', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_patient_id'), 'events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_events_product_id'), 'events', ['product_id'], unique=False)
    op.create_index(op.f('ix_events_program_id'), 'events', ['program_id'], unique=False)
    op.create_index(op.f('ix_events_referral_id'), 'events', ['referral_id'], unique=False)
    op.create_index(op.f('ix_events_speciality_id'), 'events', ['speciality_id'], unique=False)
    op.create_index(op.f('ix_events_subject_id'), 'events', ['subject_id'], unique=False)
    op.create_index(op.f('ix_events_subject_type'), 'events', ['subject_type'], unique=False)
    op.create_table('question_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['questionnaire_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_submission_question_answer')
    )
    op.create_index(op.f('ix_question_answers_question_id'), 'question_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_answers_submission_id'), 'question_answers', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_answers_submission_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_question_id'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index(op.f('ix_events_subject_type'), table_name='events')
    op.drop_index(op.f('ix_events_subject_id'), table_name='events')
    op.drop_index(op.f('ix_events_speciality_id'), table_name='events')
    op.drop_index(op.f('ix_events_referral_id'), table_name='events')
    op.drop_index(op.f('ix_events_program_id'), table_name='events')
    op.drop_index(op.f('ix_events_product_id'), table_name='events')
    op.drop_index(op.f('ix_events_patient_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_doctor_id'), table_name='events')
    op.drop_index(op.f('ix_events_actor_user_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_referrals_token_hash'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_speciality_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_source'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_record_id_snapshot'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_is_psychiatric_speciality_snapshot'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_invitation_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_doctor_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_created_by_user_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_questionnaire_submissions_status'), table_name='questionnaire_submissions')
    op.drop_index(op.f('ix_questionnaire_submissions_questionnaire_id'), table_name='questionnaire_submissions')
    op.drop_index(op.f('ix_questionnaire_submissions_program_stage_id'), table_name='questionnaire_submissions')
    op.drop_index(op.f('ix_questionnaire_submissions_program_id'), table_name='questionnaire_submissions')
    op.drop_index(op.f('ix_questionnaire_submissions_patient_id'), table_name='questionnaire_submissions')
    op.drop_table('questionnaire_submissions')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_index(op.f('ix_question_options_order_index'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_program_stage_items_stage_id'), table_name='program_stage_items')
    op.drop_index(op.f('ix_program_stage_items_speciality_id'), table_name='program_stage_items')
    op.drop_index(op.f('ix_program_stage_items_questionnaire_id'), table_name='program_stage_items')
    op.drop_index(op.f('ix_program_stage_items_order_index'), table_name='program_stage_items')
    op.drop_index(op.f('ix_program_stage_items_item_type'), table_name='program_stage_items')
    op.drop_index(op.f('ix_program_stage_items_article_id'), table_name='program_stage_items')
    op.drop_table('program_stage_items')
    op.drop_index(op.f('ix_relative_patient_links_status'), table_name='relative_patient_links')
    op.drop_index(op.f('ix_relative_patient_links_relative_id'), table_name='relative_patient_links')
    op.drop_index(op.f('ix_relative_patient_links_patient_id'), table_name='relative_patient_links')
    op.drop_table('relative_patient_links')
    op.drop_index(op.f('ix_questions_questionnaire_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_order_index'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_questionnaire_tag_links_tag_id'), table_name='questionnaire_tag_links')
    op.drop_index(op.f('ix_questionnaire_tag_links_questionnaire_id'), table_name='questionnaire_tag_links')
    op.drop_table('questionnaire_tag_links')
    op.drop_index(op.f('ix_program_tag_links_tag_id'), table_name='program_tag_links')
    op.drop_index(op.f('ix_program_tag_links_program_id'), table_name='program_tag_links')
    op.drop_table('program_tag_links')
    op.drop_index(op.f('ix_program_stages_program_id'), table_name='program_stages')
    op.drop_index(op.f('ix_program_stages_order_index'), table_name='program_stages')
    op.drop_index(op.f('ix_program_stages_day_to'), table_name='program_stages')
    op.drop_index(op.f('ix_program_stages_day_from'), table_name='program_stages')
    op.drop_table('program_stages')
    op.drop_index(op.f('ix_program_enrollments_status'), table_name='program_enrollments')
    op.drop_index(op.f('ix_program_enrollments_program_id'), table_name='program_enrollments')
    op.drop_index(op.f('ix_program_enrollments_patient_id'), table_name='program_enrollments')
    op.drop_table('program_enrollments')
    op.drop_index(op.f('ix_patient_program_access_updated_by_user_id'), table_name='patient_program_access')
    op.drop_index(op.f('ix_patient_program_access_purchase_requested'), table_name='patient_program_access')
    op.drop_index(op.f('ix_patient_program_access_program_id'), table_name='patient_program_access')
    op.drop_index(op.f('ix_patient_program_access_patient_id'), table_name='patient_program_access')
    op.drop_index(op.f('ix_patient_program_access_is_active'), table_name='patient_program_access')
    op.drop_table('patient_program_access')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_speciality_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_record_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_patient_profile_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invitation_type'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_expires_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_doctor_profile_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_created_by_user_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_accepted_by_user_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_doctor_tag_overrides_tag_id'), table_name='doctor_tag_overrides')
    op.drop_index(op.f('ix_doctor_tag_overrides_doctor_id'), table_name='doctor_tag_overrides')
    op.drop_index(op.f('ix_doctor_tag_overrides_action'), table_name='doctor_tag_overrides')
    op.drop_table('doctor_tag_overrides')
    op.drop_index(op.f('ix_doctor_patient_links_status'), table_name='doctor_patient_links')
    op.drop_index(op.f('ix_doctor_patient_links_patient_id'), table_name='doctor_patient_links')
    op.drop_index(op.f('ix_doctor_patient_links_doctor_id'), table_name='doctor_patient_links')
    op.drop_table('doctor_patient_links')
    op.drop_index(op.f('ix_content_assignments_status'), table_name='content_assignments')
    op.drop_index(op.f('ix_content_assignments_questionnaire_id'), table_name='content_assignments')
    op.drop_index(op.f('ix_content_assignments_patient_id'), table_name='content_assignments')
    op.drop_index(op.f('ix_content_assignments_assignment_type'), table_name='content_assignments')
    op.drop_index(op.f('ix_content_assignments_assigned_by_user_id'), table_name='content_assignments')
    op.drop_index(op.f('ix_content_assignments_article_id'), table_name='content_assignments')
    op.drop_table('content_assignments')
    op.drop_index(op.f('ix_contact_preferences_updated_by_user_id'), table_name='contact_preferences')
    op.drop_index(op.f('ix_contact_preferences_patient_id'), table_name='contact_preferences')
    op.drop_index(op.f('ix_contact_preferences_do_not_call'), table_name='contact_preferences')
    op.drop_table('contact_preferences')
    op.drop_index(op.f('ix_consent_records_recorded_by_user_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_patient_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_created_at'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_consent_type'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_accepted'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_article_tag_links_tag_id'), table_name='article_tag_links')
    op.drop_index(op.f('ix_article_tag_links_article_id'), table_name='article_tag_links')
    op.drop_table('article_tag_links')
    op.drop_index(op.f('ix_article_progress_patient_id'), table_name='article_progress')
    op.drop_index(op.f('ix_article_progress_article_id'), table_name='article_progress')
    op.drop_table('article_progress')
    op.drop_index(op.f('ix_webauthn_challenges_user_id'), table_name='webauthn_challenges')
    op.drop_index(op.f('ix_webauthn_challenges_expires_at'), table_name='webauthn_challenges')
    op.drop_index(op.f('ix_webauthn_challenges_challenge_type'), table_name='webauthn_challenges')
    op.drop_index(op.f('ix_webauthn_challenges_challenge'), table_name='webauthn_challenges')
    op.drop_table('webauthn_challenges')
    op.drop_index(op.f('ix_user_role_links_user_id'), table_name='user_role_links')
    op.drop_index(op.f('ix_user_role_links_role'), table_name='user_role_links')
    op.drop_table('user_role_links')
    op.drop_index(op.f('ix_speciality_tag_links_tag_id'), table_name='speciality_tag_links')
    op.drop_index(op.f('ix_speciality_tag_links_speciality_id'), table_name='speciality_tag_links')
    op.drop_table('speciality_tag_links')
    op.drop_index(op.f('ix_relative_profiles_user_id'), table_name='relative_profiles')
    op.drop_table('relative_profiles')
    op.drop_index(op.f('ix_questionnaires_title'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_pro_content'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_is_hidden'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_created_by_user_id'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_copied_from_id'), table_name='questionnaires')
    op.drop_table('questionnaires')
    op.drop_index(op.f('ix_programs_title'), table_name='programs')
    op.drop_index(op.f('ix_programs_pro_content'), table_name='programs')
    op.drop_index(op.f('ix_programs_is_popular'), table_name='programs')
    op.drop_index(op.f('ix_programs_is_hidden'), table_name='programs')
    op.drop_index(op.f('ix_programs_created_by_user_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_patient_profiles_user_id'), table_name='patient_profiles')
    op.drop_index(op.f('ix_patient_profiles_record_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_passkey_credentials_user_id'), table_name='passkey_credentials')
    op.drop_index(op.f('ix_passkey_credentials_credential_id'), table_name='passkey_credentials')
    op.drop_table('passkey_credentials')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_med_assistant_profiles_user_id'), table_name='med_assistant_profiles')
    op.drop_table('med_assistant_profiles')
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_speciality_id'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_pro_content'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_hidden'), table_name='articles')
    op.drop_index(op.f('ix_articles_created_by_user_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_action_tokens_user_id'), table_name='action_tokens')
    op.drop_index(op.f('ix_action_tokens_token_type'), table_name='action_tokens')
    op.drop_index(op.f('ix_action_tokens_token_hash'), table_name='action_tokens')
    op.drop_index(op.f('ix_action_tokens_expires_at'), table_name='action_tokens')
    op.drop_table('action_tokens')
    op.drop_index(op.f('ix_users_is_blocked'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_is_system'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_specialities_name'), table_name='specialities')
    op.drop_table('specialities')
    sa.Enum('SUPERUSER', 'PATIENT', 'DOCTOR', 'RELATIVE', 'MED_ASSISTANT', name='userrole').drop(op.get_bind())
    sa.Enum('MALE', 'FEMALE', 'OTHER', 'NOT_SPECIFIED', name='gender').drop(op.get_bind())
    sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'DETACHED', name='doctorpatientstatus').drop(op.get_bind())
    sa.Enum('ACTIVE', 'DETACHED', name='relativepatientstatus').drop(op.get_bind())
    sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='actiontokentype').drop(op.get_bind())
    sa.Enum('REGISTRATION', 'AUTHENTICATION', name='webauthnchallengetype').drop(op.get_bind())
    sa.Enum('DOCTOR', 'PATIENT', 'RELATIVE', name='invitationtype').drop(op.get_bind())
    sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitationstatus').drop(op.get_bind())
    sa.Enum('ADD', 'REMOVE', name='doctortagoverrideaction').drop(op.get_bind())
    sa.Enum('TEXT', 'NUMBER', 'BOOLEAN', 'SCALE', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', name='questiontype').drop(op.get_bind())
    sa.Enum('IN_PROGRESS', 'COMPLETED', name='questionnairesubmissionstatus').drop(op.get_bind())
    sa.Enum('RUB', 'UNIT', name='programcurrency').drop(op.get_bind())
    sa.Enum('ARTICLE', 'QUESTIONNAIRE', 'CONSULTATION', name='programitemtype').drop(op.get_bind())
    sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='programenrollmentstatus').drop(op.get_bind())
    sa.Enum('CREATED', 'LINK_SENT', 'OPENED', 'REGISTERED', 'CANCELLED', name='referralstatus').drop(op.get_bind())
    sa.Enum('KVB_DOCTOR', 'PSYCHIATRY_EXISTING', 'CHECKUP', 'OTHER', name='referralsource').drop(op.get_bind())
    sa.Enum('REFERRAL_CREATED', 'LINK_SENT', 'LINK_OPENED', 'REGISTRATION_COMPLETED', 'CONSENT_GIVEN', 'QUESTIONNAIRE_STARTED', 'QUESTIONNAIRE_COMPLETED', 'ARTICLE_READ', 'CONTACT_REQUESTED', 'ASSISTANT_CALL_ATTEMPTED', 'ASSISTANT_CONTACTED', 'APPOINTMENT_BOOKED', 'APPOINTMENT_ATTENDED', 'PACKAGE_OFFERED', 'PAYMENT_LINK_SENT', 'PACKAGE_PURCHASED', 'REFUND_CREATED', 'PROGRAM_STARTED', 'PROGRAM_COMPLETED', 'PROGRAM_IN_PROGRESS', name='eventtype').drop(op.get_bind())
    sa.Enum('PERSONAL_DATA_PROCESSING', 'MEDICAL_DATA_PROCESSING', 'ASSISTANT_CONTACT', 'ANALYTICS_PROCESSING', name='consenttype').drop(op.get_bind())
    sa.Enum('GENERAL', 'PATIENT_REGISTERED', 'ARTICLE_ASSIGNED', 'QUESTIONNAIRE_ASSIGNED', 'QUESTIONNAIRE_COMPLETED', 'CONTACT_REQUESTED', 'PROGRAM_PURCHASE_REQUESTED', 'PROGRAM_ACCESS_GRANTED', name='notificationtype').drop(op.get_bind())
    sa.Enum('ARTICLE', 'QUESTIONNAIRE', name='assignmenttype').drop(op.get_bind())
    sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='assignmentstatus').drop(op.get_bind())
    # ### end Alembic commands ###
