"""program_home_fields

Revision ID: 95f734785945
Revises: 6042112705c7
Create Date: 2026-09-07 00:43:00.920877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95f734785945'
down_revision: Union[str, Sequence[str], None] = '6042112705c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_article_analytics'))

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('invitation_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('DOCTOR', 'PATIENT', 'RELATIVE', 'MED_ASSISTANT', 'SUPERUSER', name='invitationtype'),
               existing_nullable=False)

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_start",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "home_priority",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('home_priority')
        batch_op.drop_column('is_start')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('invitation_type',
               existing_type=sa.Enum('DOCTOR', 'PATIENT', 'RELATIVE', 'MED_ASSISTANT', 'SUPERUSER', name='invitationtype'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_article_analytics'), ['subject_type', 'event_type', 'subject_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###
